verbs_rules = [
    #presente
    ('ies', 'y'),  
    ('es',  ''),
    ('s',   ''),
    #pasado
    ('ied', 'y'), 
    ('ed',  ''), 
    ('d',   ''),
    #gerundio
    ('ying', 'ie'),
    ('ing',  ''),
]

exceptions = {
    'am': 'be', 'are': 'be', 'is': 'be', 'was': 'be', 'were': 'be',
    'been': 'be', 'being': 'be',
    'has': 'have', 'had': 'have', 'having': 'have',
    'goes': 'go', 'went': 'go', 'gone': 'go', 'going': 'go',
    'does': 'do', 'did': 'do', 'done': 'do', 'doing': 'do',
    'makes': 'make', 'made': 'make', 'making': 'make',
    'could': 'can',
    'says': 'say', 'said': 'say', 'saying': 'say',
    'comes': 'come', 'came': 'come', 'coming': 'come',
    'knows': 'know', 'knew': 'know', 'known': 'know', 'knowing': 'know',
    'sees': 'see', 'saw': 'see', 'seen': 'see', 'seeing': 'see',
    'gives': 'give', 'gave': 'give', 'given': 'give', 'giving': 'give',
    'wants': 'want', 'wanted': 'want', 'wanting': 'want',
    'quickly': 'quick', 'slowly': 'slow', 'easily': 'easy',
    'hardly': 'hard', 'clearly': 'clear', 'directly': 'direct',
    'finally': 'final', 'currently': 'current', 'mainly': 'main',
    'especially': 'especial', 'generally': 'general', 'normally': 'normal',
    'naturally': 'natural', 'socially': 'social', 'culturally': 'cultural',
    'economically': 'economic', 'historically': 'historical',
    'scientifically': 'scientific', 'politically': 'political',
    'technologically': 'technological', 'radically': 'radical',
    'partially': 'partial', 'constantly': 'constant', 'completely': 'complete',
    'significantly': 'significant', 'notably': 'notable',
    'permanently': 'permanent', 'abruptly': 'abrupt',
    'exponentially': 'exponential', 'dramatically': 'dramatic',
    'alarmingly': 'alarming',

    'teeth': 'tooth', 'feet': 'foot', 'men': 'man', 'women': 'woman',
    'children': 'child', 'mice': 'mouse', 'geese': 'goose',
    'leaves': 'leaf', 'lives': 'life', 'halves': 'half',
    'knives': 'knife', 'wives': 'wife', 'theses': 'thesis',
    'analyses': 'analysis', 'crises': 'crisis', 'hypotheses': 'hypothesis',
    'phenomena': 'phenomenon', 'criteria': 'criterion', 'data': 'datum',

    'cities': 'city', 'societies': 'society', 'civilizations': 'civilization',
    'nations': 'nation', 'generations': 'generation', 'populations': 'population',
    'revolutions': 'revolution', 'traditions': 'tradition',
    'temperatures': 'temperature', 'emissions': 'emission', 'rates': 'rate',
    'levels': 'level', 'markets': 'market', 'governments': 'government',
    'banks': 'bank', 'systems': 'system', 'programs': 'program',
    'algorithms': 'algorithm', 'companies': 'company', 'investments': 'investment',
    'scientists': 'scientist', 'doctors': 'doctor', 'students': 'student',
    'professors': 'professor', 'universities': 'university',
    'institutions': 'institution', 'skills': 'skill', 'tools': 'tool',
    'methodologies': 'methodology', 'strategies': 'strategy',
    'technologies': 'technology', 'energies': 'energy', 'economies': 'economy',
    'predictions': 'prediction', 'images': 'image', 'millions': 'million',
    'billions': 'billion', 'sectors': 'sector', 'models': 'model',
    'services': 'service', 'classes': 'class', 'schools': 'school',
    'curricula': 'curriculum', 'indices': 'index', 'diseases': 'disease',
    'treatments': 'treatment', 'vaccines': 'vaccine', 'hospitals': 'hospital',
    'patients': 'patient', 'researchers': 'researcher', 'activists': 'activist',
    'fuels': 'fuel', 'glaciers': 'glacier', 'ecosystems': 'ecosystem',
    'chains': 'chain', 'cryptocurrencies': 'cryptocurrency',
    'investors': 'investor', 'workers': 'worker', 'machines': 'machine',
    'chips': 'chip', 'robots': 'robot', 'assistants': 'assistant',
    'sensors': 'sensor',

    'offered': 'offer', 'melted': 'melt', 'reached': 'reach',
    'revolutionized': 'revolutionize', 'infected': 'infect',
    'converted': 'convert', 'deteriorated': 'deteriorate', 'motivated': 'motivate',
    'expanded': 'expand', 'destroyed': 'destroy', 'signed': 'sign',
    'invested': 'invest', 'incorporated': 'incorporate',
    'identified': 'identify', 'designed': 'design', 'participated': 'participate',
    'collapsed': 'collapse', 'discovered': 'discover',
    'implemented': 'implement', 'attracted': 'attract',

    'decades': 'decade', 'celsius': 'celsius', 'hardware': 'hardware',
    'internet': 'internet', 'streaming': 'streaming'
}

reglas_morfologicas = [
    ('ies', 'y'), 
    ('ves', 'f'),
    ('es',  ''),
    ('s',   ''),
    ('est', ''),
    ('er',  ''),
]
