STOPWORDS = [
    'a', 'an', 'the', 'and', 'or', 'but', 'if', 'while', 'although',
    'because', 'as', 'until', 'unless', 'since', 'so', 'than', 'that',
    'though', 'despite', 'however', 'nevertheless', 'therefore',
    'also', 'overall', 'among', 'around', 'under', 'due',
    'of', 'to', 'in', 'for', 'on', 'at', 'by', 'from', 'with',
    'about', 'against', 'between', 'into', 'through', 'during',
    'before', 'after', 'above', 'below', 'up', 'down', 'out',
    'off', 'over', 'again', 'further', 'then', 'once',
    'i', 'me', 'my', 'myself',
    'we', 'our', 'ours', 'ourselves',
    'you', 'your', 'yours', 'yourself', 'yourselves',
    'he', 'him', 'his', 'himself',
    'she', 'her', 'hers', 'herself',
    'it', 'its', 'itself',
    'they', 'them', 'their', 'theirs', 'themselves',
    'this', 'that', 'these', 'those',
    'am', 'is', 'are', 'was', 'were',
    'be', 'been', 'being',
    'have', 'has', 'had', 'having',
    'do', 'does', 'did', 'doing',
    'can', 'could', 'should', 'would', 'may', 'might',
    'must', 'shall', 'will',
    'not', 'no', 'nor',
    's', 't', 'm', 're', 've', 'll', 'd',
    'don', 'dont', 'shouldn', 'shouldnt',
    'wouldn', 'wouldnt', 'couldn', 'couldnt',
    'won', 'wont', 'isn', 'isnt',
    'aren', 'arent', 'wasn', 'wasnt',
    'weren', 'werent', 'hasn', 'hasnt',
    'haven', 'havent', 'hadn', 'hadnt',
    'one', 'ones', 'thing', 'things',
    'something', 'anything', 'nothing',
    'someone', 'anyone', 'everyone',
    'people', 'person', 'persons',
    'make', 'makes', 'made', 'making',
    'get', 'gets', 'got', 'getting',
    'go', 'goes', 'went', 'going',
    'come', 'comes', 'came', 'coming',
    'know', 'knows', 'knew', 'known',
    'think', 'thinks', 'thought',
    'say', 'says', 'said',
    'see', 'sees', 'saw', 'seen',
    'use', 'uses', 'used', 'using',
    'want', 'wants', 'wanted',
    'need', 'needs', 'needed',
    'like', 'many', 'more', 'most',
    'much', 'very', 'just', 'even',
    'well', 'back', 'way', 'new',
    'good', 'bad', 'great',
    'first', 'last', 'long',
    'include', 'including', 'provide', 'provides',
    'continue', 'continues', 'general', 'various',
    'overall', 'example', 'information',
    'question', 'answer', 'point',
    'part', 'case', 'fact', 'reason',
    'writes', 'wrote', 'article', 'posting',
    'post', 'posted', 'reply',
    'mail', 'message', 'subject',
    'organization',
    'nntp', 'host', 'lines',
    'there', 'here', 'where', 'when', 'what', 'which', 'who', 'whom',
    'whose', 'why', 'how',
    'any', 'some', 'all', 'only', 'own', 'same', 'few', 'every',
    'another', 'other', 'others', 'else',
    'would', 'could', 'should', 'will', 'shall', 'may', 'might',
    'were', 'was', 'are', 'is', 'am', 'be', 'been', 'being',
    'really', 'probably', 'maybe', 'perhaps', 'quite', 'rather',
    'still', 'now', 'then', 'always', 'never',
    'yes', 'yeah', 'ok', 'okay',
    'im', 'ive', 'id', 'ill',
    'youre', 'youve', 'youll',
    'theyre', 'theyve',
    'hes', 'shes', 'thats', 'theres',
    'try', 'look', 'mean', 'means', 'take', 'give', 'tell',
    'find', 'found', 'put', 'keep', 'let', 'ask', 'help',
    'problem', 'problems', 'possible', 'sure',
    'line', 'lines', 'list', 'number', 'numbers',
    'name', 'names', 'time', 'times', 'year', 'years',
    'read', 'write', 'run', 'running', 'what', 'who', 'some', 'there', 'all', 'when', 'any', 
]